name: xml_rpc
version: 0.1.0
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A library to communicate through the XML-RPC protocol.
homepage: https://github.com/a14n/dart-xmlrpc
dependencies:
  crypto: '>=0.9.0 <0.10.0'
  http: '>=0.11.0 <0.12.0'
  xml: '>=2.2.0 <3.0.0'
dev_dependencies:
  unittest: any
