name: xml_rpc
version: 0.0.1-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A library to communicate through the XML-RPC protocol.
dependencies:
  crypto: any
  http: any
  xml: any
dev_dependencies:
  unittest: any
