name: xml_rpc
version: 0.2.4
description: >
  A library implementing the XML-RPC protocol.
  It provides a client allowing to make calls to servers.
homepage: https://github.com/a14n/dart-xmlrpc
environment:
  sdk: ">=2.2.2 <3.0.0"
dependencies:
  http: ^0.12.0+4
  meta: ^1.1.8
  xml: ^3.5.0
dev_dependencies:
  test: ^1.11.1
  pedantic: ^1.9.0
