name: xml_rpc
version: 0.1.4-dev
author: Alexandre Ardhuin <alexandre.ardhuin@gmail.com>
description: A library to communicate through the XML-RPC protocol.
homepage: https://github.com/a14n/dart-xmlrpc
dependencies:
  http: ^0.11.0
  xml: ^2.2.0
dev_dependencies:
  test: any
